### ISSUE TITLE
No Connection to the Friend Server

### ISSUE THREAD

**Issue by WolfSabian** [gw2scratch/arcdps-clears#22] opened 2023-03-29 20:23 UTC
Friend clears are not working for a few days now, before patch, no info from friends are being displayed with the error "No connection to the friend server."

Anyone have any info on this?

**Comment by Sejsel** [comment] 2023-03-29 20:36
This is caused by the subtokens reaching their maximum age and not refreshing correctly. I haven't had much time to look into why this happens, I couldn't find the reason quickly, it *should* be creating a new subtoken and replacing the old one after 10 months. I might give it another try in a bit, but I am unfortunately very busy right now. Sorry about that!

For now, it affects anyone who has been using the friends feature for a year or longer.

As a workaround, you could try switching to a different API key. I am not sure exactly what would happen (it's been more than a year since I wrote it), but I think there is a decent chance it will work. I believe I did think about people switching keys back then.

**Comment by Sejsel** [comment] 2023-09-05 12:50
This has been fixed on the server side as of 2023-09-05, 12:45 UTC. No addon update is needed. Sorry it took so long!

**Closed as completed by Sejsel** 2023-09-05 12:50 UTC

**Comment by WolfSabian** [comment] 2023-09-06 23:54
Thanks for the fix.
